services:
    nginx:
      image: nginx:stable-alpine
      container_name: user-crud-nginx
      ports:
        - '80:80'
      volumes:
        - .:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: user-crud-api
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www/html'
    mysql:
        container_name: user-crud-mysql
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'

volumes:
    sail-mysql:
        driver: local
